import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased montserrat min-h-screen">
        <div className="flex flex-col h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
